services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - '$DB_PORT:$DB_PORT'
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network
  app:
    depends_on:
      - mysql_db
    build: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DB_HOST: mysql_db
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: $DB_PORT
    ports:
      - 3000:3000
    networks:
      - node-network
volumes:
  mysql_db:
    driver: local
networks:
  node-network: