services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - '$DB_PORT:$DB_PORT'
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network
  app:
    depends_on:
      - mysql_db
    build: .
    container_name: app
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@mysql_db:${DB_PORT}/${DB_NAME}?schema=public
    ports:
      - 8080:8080
    networks:
      - node-network
  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
volumes:
  mysql_db:
    driver: local
networks:
  node-network: